### ISSUE TITLE
Sujeira em veículos

### ISSUE THREAD

**Issue by A-Noiva-Cadaver** [blainelife/roadmap#103]
**Descrição curta**
 Veículos ao se sujar, dão sync para outros e salva.

**Descrição detalhada**
 Ao veículo se sujar com o tempo, salvar a sujeira no sistema e até mesmo sincronizar com os outros players (vice-versa), assim dando até mais role-play imersivo do carro sujo e o dono ter que levar para lavar

**Como essa sugestão vai melhorar o servidor?**
 Daria um rp básico do básico para lavagens de carros e uma imersão do veículo sujar.

**Comment by Mad-zi** [comment]
É, também acho que seria algo interessante, com o tempo de uso do veiculo ele sujar e guardar no stats do veiculo, ao spawnar, estaria com essas stats
