### ISSUE TITLE
Animações faciais

### ISSUE THREAD

**Issue by Day-OS** [blainelife/roadmap#132]
**Descrição curta**
Adicionar animações de fala quando um personagem fala e uma lista de animações faciais. 

**Descrição detalhada**

Se tratam de duas sugestões em uma. As duas possuem sua base em algo parecido, sendo ambas baseadas em reações e animações que precisam rodar ao mesmo tempo que outras. Quanto a flag, acho que a 44 e a 45 servem bem no propósito de rodar sem interferir muito na parte de se movimentar (44 - finito; 45 - looping.).

1- Personagem falando ao digitar um diálogo. 
Há duas animações que se encaixam perfeitamente com esse cenário, sendo elas: `facials@gen_male@base mood_talking_1` e `facials@gen_female@base mood_talking_1`.

![Falando](https://cdn.discordapp.com/attachments/801907524516184075/807329174732800000/facial.gif)

2- Lista de animações faciais.
Há diversas animações faciais que funcionam bem na base do GTA V ([Lista de animações](https://cdn.discordapp.com/attachments/801907524516184075/807328457435381881/animacoes_faciais.txt)). Essas animações poderiam ser aplicadas da mesma forma que o gsign foi, numa lista.

**Como essa sugestão vai melhorar o servidor?**
Dando mais vida para os personagens, com reações físicas que não se limitam apenas ao imaginário dos jogadores.

**Comment by Porphirio** [comment]
Excelente sugestão.

**Comment by Ghostfvce** [comment]
As animações poderiam ser prolongadas conforme a quantidade de caracteres digitados (quanto menor, menor o tempo de animação e vice-versa).
