### ISSUE TITLE
Salvar e importar presets de mobílias/interiores

### ISSUE THREAD

**Issue by thug-thug** [blainelife/roadmap#139]
**Descrição curta**

A ideia é que ao terminar de mobiliar uma casa, o usuário, possa salvar toda mobília em um preset para poder importar em outra residência

**Descrição detalhada**

Após terminar todo o design da casa, o usuário iria na opção SALVAR PRESET ou algo parecido, salvaria o modelo de mobília da casa atual e poderia importar em outra casa.
O element avisou que as janelas poderiam bugar, então, na importação, o usuário recebe uma notificação que as janelas foram redefinidas, e o trabalho do usuário seria somente corrigir as partes das janelas que não importou.

**Como essa sugestão vai melhorar o servidor?**

Cara isso ajudaria muito no tempo de mobiliar, sério, seria uma coisa nível avançado demais, sem falar que as empresas teriam modelos prontos para vender.

**Comment by theburni** [comment]
Seria uma boa poder adquirir interiores pré-moldados.
Ao selecionar compra você posicionaria de acordo com o spawn, igual é hoje no sistema atual, podendo girar, mover, aumentar ou diminuir. E o exterior que seria exibido em janelas seria o do local onde compramos a mobília, e adicionar a opção de alterar o spawn!
