### ISSUE TITLE
[Animações com Objetos] adição de objeto e correção

### ISSUE THREAD

**Issue by cybernitsche** [blainelife/roadmap#148]
**Descrição curta**
Reportando como melhoria, como dito pra fazer no tópico sobre o sistema (https://forum.blaine.life/viewtopic.php?f=5&p=2869#p2869).

**Descrição detalhada**
Adição de um objeto que ainda não tem interação:

<img src="https://cdn.discordapp.com/attachments/696932809104818267/809536410822377532/unknown.png" alt="Bug" width="393" height="423">

correção de um objeto que mostra a interação, mas ela não acontece:
<img src="https://cdn.discordapp.com/attachments/696932809104818267/809536443369521152/unknown.png" alt="Bug2" width="588" height="478">

**Como essa sugestão vai melhorar o servidor?**
—

**Comment by VictorFerraresi** [comment]
Os objetos que não exibem o texto de interação ao serem selecionados pelo cursor não podem ser utilizados. É uma limitação do GTA V, então não conseguimos torná-lo interagível.

Sobre esse banco, o @fmd00 pode dar uma olhada, mas muito provavelmente apenas um lado dele ficará funcional, dado o fato de que o menu não permite (e não temos intuito de permitir) que você altere a sua rotação.
