### ISSUE TITLE
Mais animações a serem inseridas (andar, correr, chat etc)

### ISSUE THREAD

**Issue by Ghostfvce** [blainelife/roadmap#153]
**Descrição curta**
Mais animações pra serem inseridas dentro do servidor e ampliarem sua gama.

**Descrição detalhada**
**CORRER (NÃO ESTÃO COM DIREÇÕES NO FLAG COLOCADO, SOMENTE EM LINHA RETA)**
move_m@alien alien_run 35
move_m@brave run 35
move_m@brave@a run 35
move_m@casual@a run 35
move_m@casual@b run 35
move_m@casual@c run 35
move_m@casual@d run 35
move_m@casual@e run 35
move_m@casual@f run 35
move_m@chubby@a run 35 (GORDO)
move_m@copchase1 run 35 (MÃO NO COLDRE)
move_m@copchase2 run 35 (MÃO NO RÁDIO)
move_m@drunk@a run 35 (BÊBADO)
move_m@drunk@moderatedrunk run 35 (BÊBADO 2)
move_m@drunk@slightlydrunk run 35 (BÊBADO 3)
move_m@fat@a run 35 (GORDO 2)
move_m@fire run 35
move_m@flee@a run 35 (FOGE)
move_m@flee@b run 35 (FOGE)
move_m@flee@c run 35 (FOGE)
move_m@gangster@a run 35
move_m@hipster@a run 35
move_m@melee run 35
move_m@muscle@a run 35
move_m@scared@a run 35 (MEDO)

**ANDAR (IGUALMENTE SOBRE O LOOP)**
move_m@bail_bond walk 35
move_m@brave walk 35
move_m@brave@a walk 35
move_m@brave@b walk 35
move_m@business@a walk 35
move_m@business@b walk 35
move_m@business@c walk 35
move_m@buzzed walk 35
move_m@casual@a walk 35
move_m@casual@b walk 35
move_m@casual@c walk 35
move_m@casual@d walk 35
move_m@casual@e walk 35
move_m@casual@f walk 35
move_m@caution walk 35
move_m@chubby@a walk 35 (GORDO)
move_m@confident walk 35
move_m@crazy walk 35
move_m@depressed@a walk 35
move_m@drunk@a walk 35 (BÊBADO)
move_m@drunk@moderatedrunk walk 35 (BÊBADO 2)
move_m@drunk@slightlydrunk walk 35 (BÊBADO 3)
move_m@drunk@verydrunk walk 35 (BÊBADO 4)
move_m@fat@a walk 35 (GORDO 2)
move_m@femme@ walk 35
move_m@fire walk 35
move_m@gangster@a walk 35
move_m@gangster@generic walk 35
move_m@gangster@ng walk 35
move_m@hipster@a walk 35
move_m@joy@a walk 35
move_m@melee walk 35
move_m@money walk 35
move_m@muscle@a walk 35
move_m@non_chalant walk 35
move_m@plodding walk 35
move_m@quick walk 35
move_m@sassy walk 35
move_m@scared@a walk 35
move_m@shadyped@a walk 35
move_m@shy@b walk 35
move_m@swagger walk 35
move_m@swagger@b walk 35
move_m@tired walk 35
move_m@tool_belt@a walk 9
move_m@tough_guy@ walk 35
move_m@wading walk 35

** ANDAR FEMININO **
move_f@arrogant@a walk 35
move_f@arrogant@b walk 35
move_f@arrogant@c walk 35
move_f@business@a walk 35
move_f@chichi walk 35
move_f@depressed@b walk 35
move_f@drunk@a walk 35
move_f@exhausted walk 35
move_f@femme@ walk 35
move_f@sexy walk 35
move_f@sexy@a walk 35
move_f@shy@b walk 35
move_f@tough_guy@ walk 35
mini@strip_club@walk walk 35

**NÃO FORAM COLOCADOS OS SPRINTS, MAS BOA PARTE TEM**

ABORDAGEM
mp_arresting idle 9

DESALGEMAR
mp_arresting a_uncuff 0

HANDSUP
random@arrests@busted enter 2 (ajoelhado)
random@arrests idle_2_hands_up 2 (ajoelhado 2)
rcmminute2 handsup (normal, pode andar)

COVER
amb@code_human_cower@female@idle_a idle_c 9
amb@code_human_cower@female@react_cowering base_back_left 9
amb@code_human_cower@male@idle_a idle_b 9
amb@code_human_cower@male@idle_b idle_d 9
anim@heists@ornate_bank@hostages@cashier_b@ flinch_loop_underfire 9
amb@code_human_cower_stand@female@base base (ANDANDO NO COVER)
amb@code_human_cower_stand@male@idle_a idle_b (ANDANDO NO COVER 2)

CHAT
amb@world_human_hang_out_street@male_a@idle_a idle_a 0
amb@world_human_hang_out_street@male_a@idle_a idle_b 0
amb@world_human_hang_out_street@male_a@idle_a idle_c 0
amb@world_human_hang_out_street@male_a@idle_a idle_d 0
amb@world_human_hang_out_street@male_a@idle_a idle_e 0
amb@world_human_hang_out_street@male_b@idle_a idle_a 0
amb@world_human_hang_out_street@male_b@idle_a idle_b 0
amb@world_human_hang_out_street@male_b@idle_a idle_c 0
amb@world_human_hang_out_street@male_b@idle_a idle_d 0
amb@world_human_hang_out_street@male_c@idle_a idle_a 9
amb@world_human_hang_out_street@male_c@idle_a idle_b 9
amb@world_human_hang_out_street@male_c@idle_a idle_c 9
anim@heists@ornate_bank@chat_manager average_clothes 9
anim@heists@ornate_bank@chat_manager charm 9
anim@heists@ornate_bank@chat_manager fail 9
anim@heists@ornate_bank@chat_manager not_charm 9
friends@frm@ig_1 greeting_idle_a 0
friends@frm@ig_1 greeting_idle_b 0

LIMPEZA
amb@world_human_janitor@male@idle_a idle_a 9
amb@world_human_janitor@male@idle_a idle_b 9
amb@world_human_janitor@male@idle_a idle_c 9
amb@world_human_maid_clean@idle_b idle_e 9

COOPER
amb@world_human_jog_standing@female@base base 9
amb@world_human_jog@female@idle_a idle_c 35
amb@world_human_jog_standing@male@fitbase base 9
amb@world_human_jog@male@idle_a idle_a 35

EXAUSTO
/anim amb@world_human_jog_standing@male@idle_b idle_d 0
/anim amb@world_human_jog_standing@male@idle_b idle_e 0
/anim amb@world_human_jog_standing@male@idle_b idle_f 0

INSTRUMENTOS
amb@world_human_musician@bongos@male@base base 9
amb@world_human_musician@guitar@male@base base 9
amb@world_human_musician@guitar@male@idle_a idle_a 9
amb@world_human_musician@guitar@male@idle_a idle_c 9

CÂMERA
amb@world_human_paparazzi@male@base base

AMARRADO
anim@move_m@prisoner_cuffed idle

BOMB
anim@mp_fireworks place_firework_1_rocket 0

FACEPALM
anim@mp_player_intcelebrationfemale@face_palm face_palm 0
anim@mp_player_intcelebrationmale@face_palm face_palm 0

ACENAR/WAVE
friends@frj@ig_1 wave_a 0
friends@frj@ig_1 wave_b 0
friends@frj@ig_1 wave_c 0
friends@frj@ig_1 wave_d 0
friends@frj@ig_1 wave_e 0
friends@frl@ig_1 waive_a_lamar 0
friends@frl@ig_1 waive_c_lamar 0

/dstrip
mini@strip_club@private_dance@part1 priv_dance_p1 9
mini@strip_club@private_dance@part2 priv_dance_p2 9
mini@strip_club@private_dance@part3 priv_dance_p3 9

/sexo
rcmpaparazzo_2 shag_action_a 1
rcmpaparazzo_2 shag_loop_poppy 1
/sexocarro 
oddjobs@assassinate@vice@sex frontseat_carsex_loop_f 1
oddjobs@assassinate@vice@sex frontseat_carsex_loop_m 1
/chutar
melee@unarmed@streamed_core kick_close_a 0
melee@unarmed@streamed_core kick_close_b 0

/chutarchao
melee@unarmed@streamed_core ground_attack_on_spot 0
melee@unarmed@streamed_core ground_attack_0 0
melee@unarmed@streamed_core ground_attack_0_long 0

--------------------------------------------------------------------------

/socar 
melee@unarmed@streamed_core light_finishing_punch 0

/socarchao
melee@knife@streamed_core ground_attack_on_spot 0

**Como essa sugestão vai melhorar o servidor?**
Maior imersão no roleplay.

**Comment by Hayran** [comment]
Boa! Apoiado.
