### ISSUE TITLE
Usar taximetro fora de corridas e diminuição de valor do taximetro

### ISSUE THREAD

**Issue by Meirinh4** [blainelife/roadmap#160]
**Descrição curta**
Tenho trabalhado como taxista há algum tempo e vi que o taxímetro é impossível ser utilizado fora de corridas. Caso eu tenha desligado o taximetro por qualquer incidente que tenha havido In-Character, ao tentar retornar o taximetro, a minha tentativa é impossibilitada pelo sistema, forçando o jogador a ligar novamente ao taxista para então ativar o taximetro de volta. Percebi também que o valor do taximetro, contabilizado pelo tempo e pela distância, está um pouquinho alto, uma quantidade relativamente baixa, no entanto incoerente com o mundo real. Era bom que o taximetro contabilizasse SÓ a distância e não o tempo, é uma boa também. 

**Descrição detalhada**
Já disse o que tinha a dizer ali acima.

**Como essa sugestão vai melhorar o servidor?**
Vai poupar o tempo do jogador em ter que ligar para o taxista de volta. Não é algo que atrapalhe tanto a jogatina, mas é algo que ajudaria na imersão do role-play. Como existem outros sistemas com mais prioridade, pedia até que dessem mais prioridade para os outros sistemas.

**Comment by vicezone7682** [comment]
tem taxímetro?
