### ISSUE TITLE
Disponibilizar download dos personagens em arquivo XML via UCP para utilizar no rockstar editor.

### ISSUE THREAD

**Issue by Salesluc** [blainelife/roadmap#161]
**Descrição curta**
Disponibilizar o personagem em arquivo XML pela UCP serve para que você possa fazer um download desse arquivo contendo as características do seu personagem criado, podendo assim utilizar ele no editor da rockstar. Todas as características do seu boneco podem ser exportadas via menyoo e vídeos podem ser feitos com personagens reais do servidor com a utilização do editor offline da rockstar.

Isso ajuda e incentiva facções (governamentais ou não) a fazerem trailers mais elaborados pelo editor da rockstar e o seu personagem IC possa ser utilizado nesse trailer. Vai ajudar na produção de conteúdo para a divulgação geral do servidor.

**Comment by VictorFerraresi** [comment]
O XML tem um formato específico? Você tem algum exemplo?
