### ISSUE TITLE
Rework do sistema de bebidas

### ISSUE THREAD

**Issue by mago1337** [blainelife/roadmap#171]
**Descrição curta**
Retrabalhar o sistema de bebidas. 

**Descrição detalhada**

O peso de algumas bebidas não faz sentido (long neck de 330ml pesar 1KG), e não poder comprar um engradado é um pouco frustrante para os donos de negócios que precisam comprar em atacado (o item dos engradados de cerveja existe no jogo. Para outras bebidas, poderia usar um caixote de madeira genérico). Assim, quem estiver próximo do caixote/engradado pode usar um comando para 

**Como essa sugestão vai melhorar o servidor?**

Apenas traz maior facilidade para os jogadores, além de facilitar o gerenciamento do inventário.

**Comment by cybernitsche** [comment]
A ideia de um "rework" me dá liberdade de dar algumas sugestões que, na minha opinião, melhorariam muito o sistema de bebidas atual do servidor e daria mais imersão. Vou manter o formato pra respeitar a área e talvez ficar mais fácil pra comprender:

----------------------------------------------------------------------------------------------------------------------------------

**Descrição curta**
Fora as coisas já citadas no corpo principal
• Saciação de cede quando ingerir bebida alcoólica
• Adicionar um sistema de "ficar bêbado", que pode demorar mais ou menos dependendo da bebida.

**Descrição detalhada**
• Saciação de cede quando ingerir bebida alcoólica
No sistema atual de sede do servidor, o personagem não é saciado com bebidas alcoólicas por algum motivo. Eu não vejo isso como algo positivo. Algumas vezes eu já me peguei em uma festa ou fazendo um simples rp de beber cerveja no dia-a-dia e recebi uma notificação de estar com sede. Eu não vejo o porquê de não adicionar a saciação a cervejas, tornaria bem mais interessante, além  de casar com a segunda parte dessa sugestão:

• Adicionar um sistema de ficar bêbado
Com as bebidas alcoólicas matando a sede, ainda não seria totalmente a melhor forma de matar a sede pra quem só precisa disso, como entrar em uma 24/7, comprar, beber e já era. A ideia é as bebidas alcoólicas saciarem menos a sede do que outras bebidas normalmente vistas no servidor, sendo: água, a que mais mata sede; vindo na frente do Sprunk; que vem antes das cevejas e por fim as bebidas mais forte (vodka, conhaque, vinho, etc), que saciam cada vez menos de acordo com quanto mais forte ela é, e deixa bêbado ainda mais rápido.

Nada de ficar bêbado com só uma cerveja. Nesse caso deve ser realmente resultado de um abuso da bebida, diferente de bebidas mais fortes que talvez 1 ou 2 shots te deixaria meio "tonto" depois de um tempo. Mas interpretar isso também vai totalmente da capacidade máxima de álcool suportada do personagem de acordo com o jogador. Eessa sugestão poderia também já servir de base pra um futuro sistema de bafômetro, onde o status das bebidas ingeridas que somam pra deixar a pessoa bêbada, mantenha no corpo por alguns minutos ou horas e apite caso essa pessoa seja parada pela PD e passe pelo sistema.

**Como essa sugestão vai melhorar o servidor?**
A minha sugestão passa longe de ser algo essencial pro servidor nesse momento e não é necessário entrar em vigor junto com a sugestão principal aqui, mas é algo que eu vejo ser interessante de ser implementado. Matar a sede daria uma utilidade melhor as bebidas, e deixar bêbado aumentaria a imersão, visto que algumas pessoas esquecem de interpretar o resultado do abuso de álcool, isso meio que poderia servir como um "lembrete" dela interpretar.

**Comment by vanessa** [comment]
@mago1337 Isso seria uma duplicata de https://github.com/Blaine-Life/blaine-issues/issues/207?

**Comment by mago1337** [comment]
> @mago1337 Seria #207 uma duplicata dessa issue?
Somente a sugestão do @cybernitsche, a minha não. É mais sobre os pesos dos itens e gerenciamento de inventário com engradados, por exemplo.
