### ISSUE TITLE
/batom, /blush, /delineado, etc - Remover maquiagens.

### ISSUE THREAD

**Issue by sentinel5959** [blainelife/roadmap#177]
**Descrição curta**
Seria bom comandos que pudessem ser usados para remover maquiagem dos personagens, semelhante aos comandos de tirar roupas como /jaqueta, /sapatos, /calcas mas para as maquiagens.

**Descrição detalhada**
N/A.

**Como essa sugestão vai melhorar o servidor?**
Para personagens femininos isso é importante, ninguém anda maquiada 24 horas por dia... Talvez andem mas devem ser uma quantia baixa... não é?

**Comment by cybernitsche** [comment]
Uma ótima sugestão pra vir junto com essa seria poder mudar a maquiagem em algum lugar, assim como podemos mudar o cabelo. Creio que não seja algo complicado, já que há uma seção só pra isso na criação de personagem. Seria como exportar essa seção da criação pra um /comprar em uma loja.
