### ISSUE TITLE
Sistema de uniforme

### ISSUE THREAD

**Issue by mago1337** [blainelife/roadmap#212]
**Descrição curta**

Um sistema que seta roupas pré-definidas para jogadores em facções ou companhias.
**Descrição detalhada**

Criar a possibilidade de compartilhar as roupas utilizadas (do mesmo gênero) com outros jogadores via um sistema de uniforme. Não tem muito o que explicar. Serve pra LSPD, segurança, bartender, etc. Dessa forma a roupa de trabalho também não ocupa um slot das roupas.

**Como essa sugestão vai melhorar o servidor?**

QoL

**Comment by cybernitsche** [comment]
Boa a sugestão. Seria interessante colocar uns 2 slots de uniforme assim como slots de roupa, e na hora de salvar ficar um embaixo do outro e podendo ser trocado com /uniformes. Acabaria liberando alguns slots a mais pra quem não tem um trabalho que necessite de uniforme, mas pra quem usa seria muito bom. Eu mesmo já me limitei slots de roupa por ter que deixar uniformes salbos.

**Comment by A-Noiva-Cadaver** [comment]
Sim, por favor. Os outfits que tenho é para cada tipo de ocasião e é muito doloroso ter que destruir um só para fazer o uniforme do trabalho.. . Acho que poderiam criar um outfit especial só para o serviço da pessoa, seja lspd, lsfd, weazel news e dentre outros milhões que irão surgir futuramente (se irão surgir né)
