### ISSUE TITLE
Espingarda não-letal (beanbag) para LSPD

### ISSUE THREAD

**Issue by doougl4s** [blainelife/roadmap#217]
**Descrição curta**
Criar uma arma não letal para LSPD para controle de disturbios civis

**Descrição detalhada**
Adicionar a possibilidade de conversão da espingarda calibre 12 em não letal através do comando /beanbag dentro do veículo ou no porta-malas OU adicionar uma arma nova, com skin igual usada pela LAPD (coronha e guarda mão na cor verde)

https://pt.gta5-mods.com/weapons/bean-bag-shotgun-nee__

**Como essa sugestão vai melhorar o servidor?**
Vai possibilitar que a LSPD lide com situações sem precisar dar tiros de arma de fogo.

**Comment by mago1337** [comment]
[Corrigindo o link da issue.](https://pt.gta5-mods.com/weapons/bean-bag-shotgun-nee__)
