### ISSUE TITLE
Acessórios de Armas para LSPD

### ISSUE THREAD

**Issue by doougl4s** [blainelife/roadmap#221]
**Descrição curta**
Permitir acoplar acessórios nas armas da LSPD

**Descrição detalhada**
Permitir que a LSPD acople acessórios nas armas (lanternas, mira a laser, etc)

**Como essa sugestão vai melhorar o servidor?**
Vai permitir que a LSPD tenha armas mais reais, com lanternas e miras, etc

**Comment by Mad-zi** [comment]
Acho uma ideia excelente, inclusive as miras holográficas, porem não ser apenas para a LSPD e poder acoplar o item "laser"/"lanterna" a respetiva arma que suporta o mesmo
