### ISSUE TITLE
Interface do Inventário

### ISSUE THREAD

**Issue by doougl4s** [blainelife/roadmap#226]
**Descrição curta**
Permitir que o Inventário seja utilizado por uma interface interativa

**Descrição detalhada**
Melhora o inventário dos jogadores, permitindo que seja visualmente mais agradável do que estando no chat.

Conceito: https://stuyk.com/athena-inventory-interface/
https://www.youtube.com/watch?v=Iy4uTjjUhsw&ab_channel=SunriseResources

**Como essa sugestão vai melhorar o servidor?**
Vai melhorar a interação e deixar no chat somente o essencial.

**Comment by A-Noiva-Cadaver** [comment]
Se vier com roupas já também para o uso, já dou uma sugestão sobre essa, claro o armário /wardrobe nas casas para o uso, ao comprar vai para o inventário e a pessoa "dropa" dentro do /wardrobe, como também itens como sapatos, chapéus, cintos e etc e etc e etc. Esse inventário eu ia dar sugestão sobre isso mas fiquei mosqueando muito para não postar mas é mt bom ter :P
