### ISSUE TITLE
Dano das Armas e Remoção do Instakill / Headshot

### ISSUE THREAD

**Issue by doougl4s** [blainelife/roadmap#228]
**Descrição curta**
Editar o dano de todas as armas de fogo para que causem menos danos, fazendo os tiroteios durarem mais tempo e remover o headshot (instakill).

**Descrição detalhada**
Editar o dano de todas as armas de fogo para que causem menos danos, fazendo os tiroteios durarem mais tempo e remover o headshot (instakill)

https://wiki.altv.mp/wiki/Tutorial:Stream_Weapons#Edit_weapons_damages

**Como essa sugestão vai melhorar o servidor?**
Vai impedir que os tiroteios acabem muito rápido quando algum lado esteja em vantagem numérica ou utilizando hack. Além de impedir que jogadores mal intencionados abusem do headshot durante troca de tiros.

**Comment by THE-CM-PUNK** [comment]
Apoio. +5 tiros de pistola pra matar alguém é agradável. E uns danos mais altos pra cabeça. Tipo uns 3 headshot.

**Comment by thug-thug** [comment]
Sim, precisa de um sistema de dano igual ao Segunda Vida Roleplay é totalmente necessário isso com o sistema de /ferimentos
O TR3V1Z4N1 fez de forma limpa e bonitinha o sistema, caso a staff queira poupar tempo eu acharia bacana contatar ele, ele vai adorar ajudar o blaine no que puder
