### ISSUE TITLE
Camêra do Helicoptero e Spotlight LSPD

### ISSUE THREAD

**Issue by doougl4s** [blainelife/roadmap#229]
**Descrição curta**
Criar um sistema que o copiloto do helicoptero da LSPD possa utilizar a câmera, igual no GTA V singleplayer, podendo também iluminar o solo com o spotlight/luz.

**Descrição detalhada**
Conceito: https://www.youtube.com/watch?v=ntr_G0uWyGI&ab_channel=GTAWORLDRP

**Como essa sugestão vai melhorar o servidor?**
Vai melhorar a utilização do helicoptero da LSPD durante perseguições e tornar o jogo mais real.

**Comment by Mad-zi** [comment]
Apoio, e para as News tambem o proprio helicopreto tem uma câmera
