### ISSUE TITLE
NPC CASA/EMPRESA

### ISSUE THREAD

**Issue by THE-CM-PUNK** [blainelife/roadmap#230]
**Descrição curta**
NPC DENTRO DA CASA OU EMPRESA E POSSIBILIDADE PRA SER COLOCADO NO EXTERIOR TAMBÉM EM CERTOS METROS.

**Descrição detalhada**
O sistema de NPC é um sistema onde teríamos a possiblildade de criar NPC's do GTA V singleplayer, parecido com o modo diretor do Rockstar Editor, mas não 100%. Nesse sistema, deveríamos ter todas as animações que já existe para o personagem usando /anim ou /animlist sendo possível aplicar neles. Para aumentar o realismo, também teríamos a possibilidade de pôr nome e sobrenome do NPC desejado e até diversas frases, seja em exato momento ou instantaneamente, algo como "Bem-vindo" para um balconista ou um "Boa noite, filho" para o NPC da família de um personagem. 

**Como essa sugestão vai melhorar o servidor?**
Vejo que é um sistema muito necessário para trazer a realidade ainda maior para o GTA V, sonhando ter entre 10 a 15 NPC's por casa e empresa, buscando entregar conteúdo interessante com eles. Essa sugestão não é muito diferente do que já temos no servidor, que é o do PET. Além dessa sugestão fazer screenshots e roleplays bem-composto, creio que a fluidez e a diversificação de personagens contarão como combustível para atingir a realidade inovadora no GTA. Tópicos de facções vão ficar mais interessantes de ser acompanhado ao ver diversos NPC's sendo inseridos com suas próprias tramas, dando gosto de acompanhar. Ainda mais Inovações ao cenário interpretativo dependendo de qual empresa o NPC for utilizado. 
E é bom ressaltar que atualmente, não fica bacana acompanhar uma screenshot no tópico onde o jogador é obrigado a fazer RP com o vento, usando do /me pra ser o NPC e muitas das vezes piorando a cena ao falar sozinho. Isso seria uma correção e uma mão ajuda a esse jogador.

**Comment by THE-CM-PUNK** [comment]
OBS: Se meter só pra Premium, seria sacanagem com o que rola atualmente no servidor, mas eu não reclamaria se tivesse ao menos uns 2-3 NPC's para jogadores comum. Eu agradeço e desejo boa sorte.

**Comment by vicezone7682** [comment]
acredito que é melhor o clássico texto de entrada em cada empresa, escolhido pelo dono.
* Você nota um recepcionista que lhe dá saudações. Atrás dele, seria possível notar uma câmera de segurança em direção à porta.

**Comment by vicezone7682** [comment]
E nome e sobrenome acho uma furada. As pessoas iriam """confundir"'"" com jogadores. Melhor só um nome, mesmo.

**Comment by THE-CM-PUNK** [comment]
> E nome e sobrenome acho uma furada. As pessoas iriam """confundir"'"" com jogadores. Melhor só um nome, mesmo.

Não, nada vê. Isso é coisa do SAMP e andar pra trás não é uma coisa que o Blaine Life esteja a fim de seguir. Esse sistema entrega bem mais melhorias e acréscimos do que simplesmente uma pessoa se confundir.
