### ISSUE TITLE
Interior entrável na caravana (Camper)

### ISSUE THREAD

**Issue by Meirinh4** [blainelife/roadmap#231]
**Descrição curta**
Ter  um interior para caravana e dar pra mobiliar. 

**Descrição detalhada**
Vou deixar o LINK aqui do mesmo sitema no GTA WORLD (https://www.youtube.com/watch?v=pIPp9Pe58VU)

**Como essa sugestão vai melhorar o servidor?**
Aumentar a imersão entre os jogadores.

**Comment by Hayran** [comment]
Isso aí, bom para RP de motorhome, e acredito que não seria difícil aplicar esse sistema.
