### ISSUE TITLE
Menu de empresas abertas

### ISSUE THREAD

**Issue by Maict** [blainelife/roadmap#234]
**Descrição curta**
Facilitar os jogadores a saber as empresas que estão com status de funcionamento. Como um google maps atualmente.

**Descrição detalhada**
Um comando vinculado ao sistema de empresas que mostra sua empresa numa lista de empresas abertas no momento, caso ela esteja aberta, claro. E ao dar enter seu GPS marca a empresa. Assim como naquele servidor famoso, básicamente. 

**Como essa sugestão vai melhorar o servidor?**
Irá facilitar o roleplay civil, facilitando a identificação de pontos de roleplay civil.

**Comment by Maict** [comment]
Casaria com esse sistema um sistema que você habilita sua empresa a aparecer nessa lista. Talvez casar esse sistema com o /trancar da empresa, assim sendo ela trancada ela sumiria da lista. Ou se preferirem, um /abrirempresa, algo do tipo.

**Comment by Maict** [comment]
> Casaria com esse sistema um sistema que você habilita sua empresa a aparecer nessa lista. Talvez casar esse sistema com o /trancar da empresa, assim sendo ela trancada ela sumiria da lista. Ou se preferirem, um /abrirempresa, algo do tipo.

não só casaria, acho que seria obrigatório. tem que ter, pra que funcione certo.

**Comment by vicezone7682** [comment]
gosto dessa
