### ISSUE TITLE
Punição maior por morrer/aceitarmorte in-game 

### ISSUE THREAD

**Issue by doougl4s** [blainelife/roadmap#239]
**Descrição curta**
Jogadores que morrerem por PK (killed by another player) e aceitarem morte devem receber uma punição maior pelo sistema.

**Descrição detalhada**
Os jogadores devem ser punidos automaticamente pelo sistema ao aceitarem morte após serem mortos por outros jogadores com: 
- Perda de todos os itens do inventário
- Perda do celular (exceto VIP)
- Perda de todo o dinheiro em mãos/carteira
- Desconto de um valor sobre o saldo do banco para pagamento dos serviços hospitalares (valor alto equiparado com as fianças do código penal)
- Bloqueio de 1h para trabalhar nos empregos secundários
- Etc

**Como essa sugestão vai melhorar o servidor?**
Vai dar mais valor a vida dos personagens e forçar o medo de morrer em situações onde o personagem tem a opção de se entregar/se render.

**Comment by vicezone7682** [comment]
perda de todo o dinheiro em mãos? _are you ouf of your mind?_

**Comment by A-Noiva-Cadaver** [comment]
É boa, isso iria evitar os carinhas de não quererem ir para cadeia ic e invetam monte de desculpas e fazem ainda um pg tremendo.

**Comment by sentinel5959** [comment]
Nem, tem gente que morre por acidente ou troll e na maioria das vezes não tem FD online ou admin pra te socorrer

**Comment by adrielcasser** [comment]
Só concordo se dropar no chão os itens após morte, para o dinheiro e itens não ter sido perdido em vão e para outros q acharem terem um bom proveito.
