### ISSUE TITLE
[Sugestão] [Script veículo] Mais de um passageiro em carros duas portas.

### ISSUE THREAD

**Issue by fabiiioh** [blainelife/roadmap#242]
**Descrição curta**
Passageiros sentando no banco de trás de carro duas portas. ( Z + click no veículo e selecionar opção passageiro ).

**Descrição detalhada**
Normalmente os carros duas portas só cabem duas pessoas dentro do mesmo, porém para uma inovação poderia ser uma idéia muito boa permitir mais pessoas entrarem naqueles bancos de trás que ninguém consegue entrar, pelo visto estão para implantar o sistema de colocar pessoas no porta-malas, poderia ser um sistema parecido, porém invés do player ficar no porta-malas ele ficaria no banco de trás dos veículos, pressionando Z, clicando no veículo e apertando na opção passageiro.

**Como essa sugestão vai melhorar o servidor?**
Dando mais interação com os jogadores, como na vida real muitas pessoas possuem carros duas portas e normalmente cabem duas a três pessoas no banco de trás, melhoraria o RP de pessoas dentro do carro, interações no mesmo, etc... se tornaria uma coisa mais real.

**Comment by Maict** [comment]
O lado ruim é se tomar hit, o cara que tá lá atrás não vai tomar dano... complicado nesse quesito

**Comment by fabiiioh** [comment]
> O lado ruim é se tomar hit, o cara que tá lá atrás não vai tomar dano... complicado nesse quesito

Talvez possa ter alguma maneira do personagem ficar sentado no banco de trás, (como se fosse aquela anim de sentar na cadeira fora do interior apertando Z e Click), onde ele controla altura etc... sabemos que quando ele está sentado ele toma dano, e a fisica dele também se junta ao objeto da cadeira... se tiver alguns ajustes até se bater sem cinto ele pode voar para fora do veículo.
