### ISSUE TITLE
Mobília - Otimização do seu sistema

### ISSUE THREAD

**Issue by Hayran** [blainelife/roadmap#248]
**Descrição curta**
Uma série de otimizações que poderão ser feita pelo sistema de mobília para o melhor trabalho dos mappers do servidor. 

**Descrição detalhada**
O sistema de mobília até que é bom, mas poderia ser otimizado para poupar tempo em relação a construção, isso porque consome muito tempo (que poderia está dedicado ao RP) para ajeitar simples itens, vamos lá para algumas que pode ser feito:

_1 - Possibilidade de colocação de coordenadas personalizada em cada eixo ou maior velocidade_

_A:_ Ao seleciona a opção "Editar posição (menu)" e abrir a sua lista, além da possibilidade atuar de se ajeitar o objeto colocando por lado, poderia ter uma caixa de mensagem para ajeitar o objeto ao apertar ENTER (ou outra tecla não usada). Por exemplo se eu colocar na coordenada, rotação Yaw (Rotação Z), eu poderia apertar ENTER abrirá uma caixa de dialogo pedindo um número, aí só entrar com uma numeração tipo (90) e assim objeto iria se rotacional 90 graus, e se fazer isso novamente e apertar ENTER em cima do Rotação Z e jogar outro número (-180) esse objeto assume essa rotação do eixo. 

_B:_ Tem outras formas de fazer isso, talvez por uma barra deslizante, ou apertar SHIFT e na hora de estiver passando nas SETAS esq ou dir, em vez de ir de 1 em 1 (0,1,2,3) esse número aumenta de 10 em 10 ao segurar SHIFT + Seta (10,20,30) assim fica mais rápido para ir até a coordenada destinada ou pelo menos próxima a ela, e estando próxima a ela eu solto o SHIFT e chego a numeração precisa que gostaria. 

_2 - Pesquisar e adicionar o objeto pelo seu número._

Além do separado pela categorias, poderia ter a possibilidade de pesquisar o objeto pelo número, por exemplo estou no menu de "Comprar mobília" e lá se apertar uma tecla ou acessar a categoria "pesquisar objeto" eu posso DIGITAR o número do objeto que quero, por exemplo escrever lá em uma caixa "9067" então vai aparecer uma listagem de objetos que tem esse número ou se aproxima, que no caso corresponde ao objeto 9067 Desconhecido (é uma cama militar), assim eu seleciono ele e faço as edições. Assim é bom que posso poupar tempo e anotar em algum lugar os objetos futuros que pode ser utilizado, ou ainda pesquisar rapidamente na WIKI e traze-lo para o jogo.

3 Editor de precisão (estilo SA-MP)

Tendo as opções "Editar posição (Editor livre)" e "Editar posição (menu)" essa seria a terceira opção chamada "Editar posição (precisão)" que funcionaria como funciona o sistema de mobília de objetos do sa-mp, que é aquela barrinha z y x onde você seleciona o que quer fazer (mover, rotacionar objeto) e assim fazer a precisão da mesma forma do editor do sa-mp; Veja o vídeo para lembrar como funciona.

https://www.youtube.com/watch?v=BkvGev_Q-eo (começa em 0:42 segundos).

Se quiser algo mais avançado pode se inspirar nesse: https://streamable.com/w7elh2

**Como essa sugestão vai melhorar o servidor?**
Vai ajudar BASTANTE na hora de mapear o objeto e facilitar e muito o trabalho de quem precisa editar os itens, hoje em dia leva muito mais tempo para mapear.

**Comment by A-Noiva-Cadaver** [comment]
Eu notei que um certo eixo X ou Y ao mover, um deles mexendo acaba dando menos velocidade, isso é uma coisa que também complica muito, você move ela e ela dá um pulo de 5 pixels, as vezes do nada, 3 a 1.
