### ISSUE TITLE
Sistema para corrigir a falta de taxistas na cidade

### ISSUE THREAD

**Issue by Mad-zi** [blainelife/roadmap#260]
**Descrição curta**
Resumindo, um sistema que use o taxi do gta v quando não tem taxis de serviço

**Descrição detalhada**
É algo bem em falta no servidor, querer uma corona e não ter nenhum taxista de trabalho para atender a chamada.
Basicamente ao dar o comando /ligar 1222, se tiver taxistas on, teria que esperar, se não entraria o sistema, no caso assim como funciona no gta off que o taxista dirige até a marcação feita no mapa.

**Como essa sugestão vai melhorar o servidor?**
Eu notei uma grande falha, querer ir em algum lugar e ser simplesmente impossível, ou apenas caminhando ou chamar algum amigo ic'ly, caso ele não esteja on, não tem outra solução se não ir caminhando, e em uma cidade GRANDE como Los Santos é impossível não ter um taxista.

**Comment by BelixKrux** [comment]
Dei uma sugestão semelhante, só que é mais pros farmadores, a ideia seria colocar ônibus circulando!

**Comment by DiegoPcooper** [comment]
É muito fácil a correção é diminuir os veiculos das demais profissões EXTIGUIR a profissão inútil de courrier, e dar uma falsa impressão aos novatos que o Taxista o salário do payday e maior. Sendo assim as pessoas vão quente pra trabalhar nisso.
