### ISSUE TITLE
Motorista sai do veiculo trancado

### ISSUE THREAD

**Issue by adrielcasser** [blainelife/roadmap#271]
**Versão do Servidor**

`Versão v1.8.3 alpha`

**Comportamento atual**

Ao trancar o veiculo (com o motorista ja dentro dele) consegue sair do veiculo como se tivesse aberto.

**Comportamento esperado**

Ao acionar a tranca, ficar impossibilitado do motorista sair até destrancar novamente as portas.

**Passos para reprodução**

Na imagem a seguir o veiculo esta trancado e o motorista consegue sair dele:
https://i.imgur.com/ea5Yegz.jpg

**Contexto**

Se o cara esta dentro de um veiculo com as portas trancadas, não era pra ele conseguir sair antes de destranca-las.

**Solução possível**

Portas trancadas = player não conseguir sair até destravalas.

**Comment by A-Noiva-Cadaver** [comment]
Isso não é um bug... É mais uma sugestão eu acho

**Comment by vitorvasc** [comment]
Consideraremos esta sugestão como melhoria: toda vez que um jogador sair de um veículo trancado o mesmo irá se destrancar.

**Comment by BelixKrux** [comment]
Gostei interessante até pros criminosos que fazem um sequestro rápido pra levar a vitima até o ATM, alguns podem fazer RP de se jogar, mas com a porta trancada fica impossível.
