### ISSUE TITLE
Maior investimento e expansão da criminalidade

### ISSUE THREAD

**Issue by GhostFromScooby** [blainelife/roadmap#274]
**Descrição curta**
A ideia consiste em facilitar, desenvolver e aumentar as possibilidades dos jogadores cometerem crimes pela cidade, sendo relacionadas as interações com outros jogadores ou até somente com os NPCs do jogo.

**Descrição detalhada**
A partir de percepções retiradas de outros servidores, a grande maioria do jogadores preferem, investem mais tempo e, de toda forma, dedicam-se mais em uma carreira de criminoso. É um fenômeno em que pode ser explicado pela ação, adrenalina, possiblidades de criar redes de relacionamento (grupos e rivais) entre jogadores, consequentemente, aumentando o engajamento dentro do jogo. **A possiblidade de poder e ascensão social**, com quase certeza, é o que vai fazer aquele jogador manter-se no jogo, alias, esta é uma característica mais abrangente ainda, ela é **humana**. Logo, abaixo listarei algumas coisas que considero importantes serem observadas no servidor:

- Facilitar o acesso de armas dentro do jogo;
- Destacar os maiores criminosos em um lugar específico da plataforma do servidor a partir da popularidade do mesmo;
-  Guerras territoriais;
- Possibilidade de serviços sem a necessidade de interação com outro jogador. Exemplo: o jogador, intitulado de alguma forma ladrão, conseguir serviços de assaltos a NPCs 'spawnados' em marcações no mapa para ele;
- Adicionar um incentivo a criminalidade: quanto mais crimes ele comete, mais ganhará com isso, porém a pena quando ser pego é bem maior;
- Serviços de hacker, contrabando, assaltos a estabelecimentos, traficante de órgãos etc;

**Como essa sugestão vai melhorar o servidor?**
Apesar de não ser meu estilo de jogo (prefiro jogar de civil, porém, ficaria muito melhor se também houvesse um sistema que beneficiasse proporcionalmente o quanto você trabalha, como por exemplo colocar níveis nas profissões. Um fazendeiro já experiente, ganhará muito mais do que um iniciante no ramo), não posso negar que a maior movimentação — de longe — que observo nos servidores é o mundo da "policia VS ladrão". Pode parecer até que o servidor ficará mais bagunçado, no entanto, é justamente essa sensação de perigo, tiroteio e preocupação que acaba chamando mais a atenção da maioria, consequentemente, fazendo com que a polícia e o serviço médico possam ter oportunidades de serviços frequentemente.

**Comment by vanessa** [comment]
Boa ideia. Estaremos considerando isso para desenvolvimento em breve.
