### ISSUE TITLE
Profissão "Caçador de Tesouros"

### ISSUE THREAD

**Issue by SrMERLINI** [blainelife/roadmap#278]
**Descrição curta** Profissão de caçador de tesouros se basea em checkpoint's aleatórios em que o jogador poderia passar e encontrar algo de interesse.

**Descrição detalhada**
O mundo subaquático do GTA V é INCRIVEL! Tem de tudo lá no fundo do mar... Poderia ter um sistema de caçador de recompensas... O cara mergulha e conforme passa em checkpoint's aleatórios tem uma probabilidade dele encontrar um item... Esse item poderia ser vendido entre os jogadores... As probabilidades seriam Beeem baixas mas não impossiveis...
Esses itens seriam dropaveis e o player poderia usar como decoração
Essa sugestão não precisa se prender ao universo subaquático... Também há a imensidão do deserto!

Alguns eventos poderiam ser divulgados pela mídia falando sobre acidentes que aconteceram no passado e suas raridades que se perderam próximo a lugares específicos...

**Como essa sugestão vai melhorar o servidor?**
Descentralizaria o RP "Policia e Ladrão" uma profissão que explora o cenário do game e traria muita imersão para quem quisesse fazer o RP em questão.

**Comment by GhostFromScooby** [comment]
Aproveitando o mesmo script poderia ter biólogo marinho e mergulhador. Com um sistema de níveis de profissões, na minha opinião, fica muito bom!

**Comment by BelixKrux** [comment]
Apesar de não tá no formato correto, eu apoio essa ideia de emprego.

Tem algo para o player fazer durante o "nada pra fazer" sem preconceitos por ser algo interessante para todos. 

Incrementando ele poderia vender para uma loja próximo do local de onde pega o emprego.

E a chance de achar itens dopáveis de decoração seria de 5% algumas casas teriam esses itens raros e o criminoso sortudo poderia encontrar.
