### ISSUE TITLE
Sistema de desmanche + seguros

### ISSUE THREAD

**Issue by SrMERLINI** [blainelife/roadmap#284]
**Descrição curta**
Sistema de desmanche interligado com o sistema de seguros e o de tunning. 

**Descrição detalhada**
Como base temos o sistema de tunning que é caro por natureza... Quando um carro tunado fosse desmanchado, ele poderia retornar peças de reparo e também/talvez alguma peça de tunning. Os seguros poderiam cobrir certos tipos... Seguro A cobriria apenas peças de reparo; Seguro B cobriria peças de reparo e paintjob's; seguro C cobriria Peças, PaintJob's e tunning's genética.
A profissão de desmanchador deveria ser obtida através de aplicação no fórum sob avaliação de um GM+

**Como essa sugestão vai melhorar o servidor?**
incentivaria o jogador a comprar um seguro para seu carro personalizado aumentando os cursos para manter um veiculo e dando mais RP para oficinas.

**Comment by vanessa** [comment]
Insight adicionado no card já existente https://portal.blaine.life/c/9-desmanche-de-carros
