### ISSUE TITLE
/g, /me e /do serem vistos de dentro de casa e vice-versa.

### ISSUE THREAD

**Issue by sentinel5959** [blainelife/roadmap#85]
**Descrição curta**
Se um player se aproximar da porta de uma residência e realizar um comando /me, /do ou gritar na frente da porta, quem estiver dentro do interior conseguiria ouvir e ver as interpretações. O mesmo vale para quem estiver dentro de casa, se a pessoa realizar /me's ou /do's **perto da porta** o roleplay poderia ser visto por quem está do lado de fora, com exceção de gritos que poderiam ser ouvidos do lado de fora independente se a pessoa estivesse perto da porta ou não.

**Descrição detalhada**
N/A.

**Como essa sugestão vai melhorar o servidor?**
Aumentaria o realismo dentro do servidor podendo interpretar brigas dentro de casa e serem ouvidas por vizinhos, a polícia realizar buscas em casas, invasões domiciliares, etc.

**Comment by thug-thug** [comment]
Adicionar o /gritar e chat normal se possível e com um range da porta específico.
