### ISSUE TITLE
/atributos

### ISSUE THREAD

**Issue by Drerodrigues92** [blainelife/roadmap#89]
**Descrição curta**
Um comando /atributos e /catributos (checar atributos) com informações importantes do personagem, como altura, peso, idade aproximada e outras características marcantes.

**Descrição detalhada**
Nil

**Como essa sugestão vai melhorar o servidor?**
É importante que cada um descreva atributos e características marcantes do seu personagem para outros players. Essas informações são relevantes para o RP policial (como descrever um suspeito), e também para os outros players porque isso dá um toque mais pessoal aos seus personagens.

**Comment by vitorvasc** [comment]
Atualmente existe o /aparencia, porém ainda não é salvo no banco de dados.

Adicionado no backlog tarefa para que o item passe a salvar.
